#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "FreeBSD" {
    insmod ufs1 ufs2
    set root=(hd0,3)
    search --no-floppy --fs-uuid --set 46fe0d80b56c6af0
    drivemap -s (hd0) ${root}
    chainloader +1
}
